---
author: 'Keanu Rochette '
date: '`r format(Sys.Date())`'
title: Oceanographic Data Metadata
output: github_document
---

# Cruise Information 
**PI**: Craig Nelson  
**Ship**: Kilo Moana  
**Cruise ID**: KM2315  
**Dates**: 2023-09-23 to 2023-09-26  

**Station Locations**:  

- Station A:  21 21.28 N, 158 08.90 W  
- Station B:  21 20.62 N, 158 11.86 W  
- Station C:  21 18.08 N, 158 21.92 W  
- Deep Cast:  21 14.27 N, 158 36.42 W  


## 2023-09-23 Cast

Location: Station A  
Arrival - 2100  
CTD downcast - 2130  
CTD upcast - 2200  
DCM Depth: 100-110 m (no additional DCM sampled)  
DO Max: 85-100 m  
Particle layer: 25-40 m, unstratified  
MLD: 80m (continuous density stratification of 0.5 kg/m3)  
Data file: KM2315_A_1_200m.hex  



## 2023-09-24 Casts

Location: Station B  
Arrival - 0030  
CTD downcast - 0300  
CTD upcast - 0330  
DCM Depth: 85-100m (93m sampled)  
DO Max: 60-80 m  
Particle Layer - none  
MLD: 55m  
Data file: KM2315_B_1_250m.hex  

Location: Station C  
Arrival - 0500  
CTD downcast - 1000  
CTD upcast - 1010  
DCM Depth: 110 - 155m (Sampled 132m)   
DO Max: 90 - 110m  
Particle Layer: 5 - 20m   
MLD: 75m  
Data file: KM2315_C_1_250m.hex  

Location: Station C (2)  
Arrival: NA  
Downcast - 1520  
Upcast - NA  
DCM Depth: 120 -127m (sampled 120m)  
DO Max: 80 m  
Particle layer: none  
MLD: 55m  
Data file: KM2315_C_2_250m.hex  

Location: B (2)  
Arrival - 2045  
CTD downcast - 2050  
CTD upcast - 2105  
DCM Depth: 85-95m (sample 88m)  
DO Max: 70-85m  
Particle Layer: none  
MLD: 35m  
Data file: KM2315_B_2_250m.hex  

Location: Station A (2)  
Arrival - 2145  
CTD downcast - 2200  
CTD upcast - 2208  
DCM Depth: 102 - 120m (sampled 107m)   
DO Max: 75 - 110m  
Particle Layer: 75m  
MLD: 70m  
Data file: KM2315_A_2_200m.hex  


## 2023-09-25 Cast  

Location: Deep Cast Station   
Arrival - 1830  
CTD downcast - 1900  
CTD upcast - 2000 (interrupted by hydraulic spill)  
DCM Depth: 121-128m (sampled 115m)  
DO Max: 80-110m  
Particle Layer: none  
MLD: 68m  
Data file: KM2315_D_1500m.hex  


